# Generated by Django 6.0.6 on 2026-06-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='vectorized',
            field=models.BooleanField(default=False),
        ),
    ]
