# Generated by Django 6.0.6 on 2026-06-15 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_imagemetadata_vectorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
